-- =================================================================================
-- PROYECTO: PlanIA
-- ARCHIVO: database/sample_projects.sql
-- COPYRIGHT: © 2026 Fondo Thoth AC.
-- DESCRIPCIÓN: Datos de ejemplo con 3 proyectos de negocio
-- =================================================================================

-- Proyecto 1: Cositas (Marketplace de productos artesanales)
INSERT INTO proyectos_negocio (
    uuid_usuario,
    estatus_proyecto,
    a1_nombre_negocio,
    a2_nombre_emprendedor,
    a4_carta_presentacion,
    b1_descripcion_negocio,
    b2_problema_oportunidad,
    b3_propuesta_valor,
    b4_cliente_objetivo_resumen,
    b5_monto_solicitado,
    d1_segmento_cliente,
    d5_ventaja_competitiva,
    d6_latitud,
    d7_longitud,
    d8_direccion_formateada,
    e1_proceso_produccion,
    e2_capacidad_produccion,
    e3_productos_bom_json,
    g5_costos_fijos_mensuales,
    g8_inversion_inicial,
    f2_estrategia_precios,
    f4_estrategia_promocion,
    h1_impacto_social,
    h2_impacto_economico
) VALUES (
    'demo-user',
    'completo',
    'Cositas - Marketplace Artesanal',
    'María Elena Rodríguez',
    'Soy artesana de tercera generación. Mi familia ha creado productos únicos por más de 60 años. Ahora quiero llevar estas tradiciones al mundo digital.',
    'Cositas es una plataforma móvil que conecta a artesanos locales con compradores que buscan productos únicos y hechos a mano. Ofrecemos desde joyería artesanal hasta textiles tradicionales.',
    'Los artesanos locales tienen dificultad para llegar a nuevos mercados. Las ferias son limitadas y los intermediarios reducen sus ganancias hasta un 50%.',
    'Conexión directa artesano-comprador con comisión justa del 10%, garantía de autenticidad, y envío a todo México en 3-5 días.',
    'Millennials y Gen Z interesados en productos sustentables',
    150000.00,
    'Jóvenes profesionales de 25-40 años, nivel socioeconómico ABC+, residentes en zonas urbanas, con conciencia social y preferencia por productos locales y sustentables.',
    'Somos la única plataforma que verifica la autenticidad de cada artesano y ofrece la historia detrás de cada producto. Tenemos acuerdos exclusivos con 50+ artesanos de Sonora.',
    29.0729,
    -110.9559,
    'Hermosillo, Sonora, México',
    'Los artesanos crean sus productos de forma tradicional. Cositas verifica autenticidad, fotografía los productos, y los lista en la app. Cuando hay una venta, el artesano empaca y Cositas coordina el envío.',
    '200 productos nuevos por semana, 500+ artesanos activos',
    '[{"producto": "Joyería Artesanal", "precio_venta": 450, "insumos": [{"nombre": "plata", "cantidad": 10, "unidad": "g", "costo": 80}]}, {"producto": "Textiles Bordados", "precio_venta": 850, "insumos": [{"nombre": "hilo", "cantidad": 5, "unidad": "m", "costo": 50}]}, {"producto": "Cerámica Talavera", "precio_venta": 350, "insumos": []}]',
    25000.00,
    150000.00,
    'Precios establecidos por los artesanos con una comisión del 10% para la plataforma. Descuentos del 5% por compras mayores a $1,000.',
    'Redes sociales (Instagram, TikTok), influencers de lifestyle mexicano, ferias artesanales como punto de contacto inicial.',
    'Preservación de tradiciones artesanales, generación de ingresos dignos para más de 500 familias artesanas, reducción de intermediarios.',
    'Derrama económica mensual de $500,000+ directamente a comunidades artesanas. Creación de 10 empleos directos y 50+ indirectos.'
);

-- Proyecto 2: TacoMaster - Food Truck Gourmet
INSERT INTO proyectos_negocio (
    uuid_usuario,
    estatus_proyecto,
    a1_nombre_negocio,
    a2_nombre_emprendedor,
    a4_carta_presentacion,
    b1_descripcion_negocio,
    b2_problema_oportunidad,
    b3_propuesta_valor,
    b4_cliente_objetivo_resumen,
    b5_monto_solicitado,
    d1_segmento_cliente,
    d5_ventaja_competitiva,
    d6_latitud,
    d7_longitud,
    d8_direccion_formateada,
    e1_proceso_produccion,
    e2_capacidad_produccion,
    e3_productos_bom_json,
    g5_costos_fijos_mensuales,
    g8_inversion_inicial,
    f2_estrategia_precios,
    f4_estrategia_promocion,
    h1_impacto_social,
    h2_impacto_economico
) VALUES (
    'demo-user',
    'revision_ia',
    'TacoMaster - Tacos Gourmet',
    'Carlos Mendoza Figueroa',
    'Chef con 15 años de experiencia en restaurantes de alta cocina. Mi sueño es llevar tacos de calidad gourmet a las calles de Hermosillo a precios accesibles.',
    'Food truck especializado en tacos gourmet con ingredientes premium: cortes Angus, mariscos frescos del Mar de Cortés, y salsas artesanales. Servicio rápido en zonas de oficinas.',
    'En Hermosillo hay escasez de opciones de comida rápida de calidad. Los trabajadores de oficina tienen pocas alternativas saludables y deliciosas para el almuerzo.',
    'Tacos de calidad restaurante en formato street food. Ingredientes frescos, preparación en vivo, y servicio en menos de 5 minutos.',
    'Profesionistas 25-45 años, zonas corporativas',
    85000.00,
    'Empleados de oficina en zonas como Pitic, Metrocentro y Centro. Personas de 25-50 años con ingreso medio-alto que buscan calidad y rapidez.',
    'Único food truck con certificación de manejo higiénico, ingredientes premium verificables, y chef con experiencia en alta cocina.',
    29.0865,
    -110.9541,
    'Zona Pitic, Hermosillo, Sonora',
    'Compra de ingredientes frescos cada mañana en mercado local. Preparación de salsas y marinados en cocina central. Cocción en food truck con plancha profesional.',
    '300 tacos por día, 6 días a la semana',
    '[{"producto": "Taco Angus", "precio_venta": 75, "insumos": [{"nombre": "carne angus", "cantidad": 80, "unidad": "g", "costo": 35}, {"nombre": "tortilla", "cantidad": 2, "unidad": "pz", "costo": 3}]}, {"producto": "Taco Camarón", "precio_venta": 85, "insumos": [{"nombre": "camarón", "cantidad": 60, "unidad": "g", "costo": 40}]}, {"producto": "Taco Arrachera", "precio_venta": 65, "insumos": [{"nombre": "arrachera", "cantidad": 80, "unidad": "g", "costo": 28}]}]',
    18000.00,
    85000.00,
    'Precios premium justificados por calidad. Orden individual $65-85, combo 3 tacos + bebida $180. Descuentos corporativos para pedidos de 10+.',
    'Instagram con fotos de preparación, alianzas con empresas para días de food truck, presencia en eventos y festivales.',
    'Compra directa a pescadores locales y proveedores regionales. Generación de 5 empleos directos.',
    'Ventas proyectadas de $450,000 mensuales. Apoyo a la economía local con compras de $150,000 mensuales a proveedores.'
);

-- Proyecto 3: EcoLimpia - Servicios de Limpieza Ecológica
INSERT INTO proyectos_negocio (
    uuid_usuario,
    estatus_proyecto,
    a1_nombre_negocio,
    a2_nombre_emprendedor,
    a4_carta_presentacion,
    b1_descripcion_negocio,
    b2_problema_oportunidad,
    b3_propuesta_valor,
    b4_cliente_objetivo_resumen,
    b5_monto_solicitado,
    d1_segmento_cliente,
    d5_ventaja_competitiva,
    d6_latitud,
    d7_longitud,
    d8_direccion_formateada,
    e1_proceso_produccion,
    e2_capacidad_produccion,
    e3_productos_bom_json,
    g5_costos_fijos_mensuales,
    g8_inversion_inicial,
    f2_estrategia_precios,
    f4_estrategia_promocion,
    h1_impacto_social,
    h2_impacto_economico
) VALUES (
    'demo-user',
    'borrador',
    'EcoLimpia - Limpieza Sustentable',
    'Ana Sofía Hernández',
    'Madre de 3 hijos y defensora del medio ambiente. Después de investigar los químicos dañinos en productos de limpieza comunes, decidí crear una alternativa segura para familias y mascotas.',
    'Servicio de limpieza residencial y comercial utilizando exclusivamente productos biodegradables y técnicas de bajo consumo de agua. Incluye limpieza profunda, mantenimiento y sanitización.',
    'Los servicios de limpieza tradicionales usan químicos tóxicos que afectan la salud de familias, mascotas y el medio ambiente. Hay demanda creciente por alternativas ecológicas.',
    'Limpieza profesional sin químicos tóxicos. Productos 100% biodegradables, personal capacitado, y garantía de satisfacción. Servicio que cuida tu hogar y el planeta.',
    'Familias con niños y mascotas, hogares conscientes',
    50000.00,
    'Familias con niños pequeños y/o mascotas, residentes de fraccionamientos residenciales de nivel medio-alto, personas con alergias o sensibilidad a químicos.',
    'Somos la única empresa de limpieza en Hermosillo certificada como 100% ecológica. Fabricamos nuestros propios productos con ingredientes naturales verificados.',
    29.0983,
    -110.9420,
    'Col. Las Quintas, Hermosillo, Sonora',
    'Fabricación de productos de limpieza en laboratorio propio. Capacitación continua del personal en técnicas ecológicas. Servicio con equipos de bajo consumo.',
    '15 hogares por día, 5 equipos de 2 personas',
    '[{"producto": "Limpieza Básica (depto)", "precio_venta": 450, "insumos": [{"nombre": "productos eco", "cantidad": 1, "unidad": "kit", "costo": 80}]}, {"producto": "Limpieza Profunda", "precio_venta": 850, "insumos": [{"nombre": "productos eco", "cantidad": 2, "unidad": "kit", "costo": 160}]}, {"producto": "Sanitización Completa", "precio_venta": 1200, "insumos": [{"nombre": "desinfectante natural", "cantidad": 3, "unidad": "lt", "costo": 200}]}]',
    35000.00,
    50000.00,
    'Precios competitivos con servicios tradicionales. Limpieza básica desde $450, profunda desde $850. Planes mensuales con 15% de descuento.',
    'Marketing en redes sociales enfocado en mamás y familias eco-conscientes. Alianzas con tiendas orgánicas y veterinarias. Programa de referidos.',
    'Empleo justo para 10 personas, capacitación en técnicas ecológicas, reducción de contaminantes en hogares. Productos seguros para niños y mascotas.',
    'Ingresos proyectados de $200,000 mensuales. Reducción del uso de químicos tóxicos en 500+ hogares. Creación de empleos formales con prestaciones.'
);

SELECT CONCAT('✅ Insertados ', COUNT(*), ' proyectos de ejemplo') AS resultado FROM proyectos_negocio WHERE uuid_usuario = 'demo-user';
